### ISSUE TITLE
can bad input be rejected?

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#11]
I have a dropdown where I want only items in the dropdown to stay in the edit field. For example, if my dropdown list had
1
2
3
4
5
and the user entered 6, the dropdown won't register the 6, which is correct, but it also doesn't reject the 6 entirely and empty the input. Is there an option to allow for that?

**Comment by Macacoazul01** [comment]
If you don't need to add items on the list, you can just set `addMode: false`.

If you need to, currently there isn't a parameter to "block user additions based on some rule" (this would be a nice update).

**Comment by Macacoazul01** [comment]
Currently you can create some type of rule on the `onAddItem` parameter (and if you achieve what you looking for using just it, please share here, so we can add in the examples or start implementing some upgrades in the package).

**Comment by mauricev** [comment]
I want it to work like [https://selectize.dev/docs/demos/single-item-select](url). When the user types an invalid entry and clicks outside of widget, the invalid item is deleted from the screen. I'm not sure how the additem parameter could help with this.

**Comment by Lorenzobettega** [comment]
You can put a function on the onAddItem parameter to check if the added item is valid. If not, them delete it

**Comment by mauricev** [comment]
I am sorry, but I am not following. Isn't the function for onAdditem the very function that adds the item, meaning it's not already added when the function is called, so how can it delete it?

**Comment by Macacoazul01** [comment]
I'll add a parameter to block the add based on a rule on the next version

**Comment by Macacoazul01** [comment]
Added in 2.3.0
There are still some problems (only visual) on the multiple drop widget and i wanna change the implementation later.
If you can and want to, i'm gonna open another issue to track this problem. Feel free to send a PR!

**Comment by mauricev** [comment]
This is not the behavior I am expecting. When addmode is set to _false_ and then when a user types something not in the list and clicks outside the dropdown, the typed text should clear.

**Comment by Macacoazul01** [comment]
So if this is the objective, the title isn't the best

I'm gonna create a new issue
