### ISSUE TITLE
disabling the widget

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#17]
how can i disable the widget? It doesn't seem to have an enabled flag.

**Comment by Macacoazul01** [comment]
What's the objective here by disabling?

**Comment by Macacoazul01** [comment]
Currently it isn't possible to disable a SearchBar widget in flutter (the one that we use on single choice). So we'll need to open an issue in flutter repo.

**Comment by mauricev** [comment]
[Here you go](https://github.com/flutter/flutter/issues/136943)

**Comment by Macacoazul01** [comment]
@mauricev tomorrow maybe i can try implementing the change on the widget to see if this solves the problem
If so, i'm gonna open a PR on flutter

**Comment by Macacoazul01** [comment]
If not i'll need to wait the team

**Comment by Macacoazul01** [comment]
@mauricev fixed the PR.

**Comment by Macacoazul01** [comment]
@mauricev it was approved and it is already on master channel.
Waiting for it to land on stable.

You can help by opening a request for this to be added on latest stable

**Comment by Macacoazul01** [comment]
@mauricev im not sure if it is avaliable on the latest 3.19 stable (didnt find in the changelog).
Can you check if is on beta branch?

**Comment by Macacoazul01** [comment]
@mauricev its avaliable now on 3.22.

Gonna update the package this week

**Comment by Macacoazul01** [comment]
avaliable in 5.0.0
