### ISSUE TITLE
[help wanted] Code Documentation

### ISSUE THREAD

**Issue by Macacoazul01** [Lorenzobettega/simplesearchdropdown#20]

**Comment by erickNjuki** [comment]
I can help..provide me with a description of what's needs to be done

**Comment by Macacoazul01** [comment]
There are no comments on the variables, files, classes and functions explaining what the code does.
Using this file from url_launcher as a sample:
https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher/lib/src/types.dart

**Comment by Macacoazul01** [comment]
You can look at another big flutter packages (or files from this one) to see what we're talking about.
unfortunately I won't have the time to solve this issue on the next weeks, If you're able to fix this problem, that will help a lot the package!

**Comment by Macacoazul01** [comment]
@erickNjuki we started documenting the code.
The single dropdown is almost finished, but we need help on the multiple one
