### ISSUE TITLE
No element error 

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#21]
In 3.1.1, when I select an entry in the list and then delete a character by typing the delete key, I get the following

```
======== Exception caught by widgets ===============================================================
The following StateError was thrown while calling onChanged:
Bad state: No element

When the exception was thrown, this was the stack: 
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      OverlayScreen.updateLast (package:simple_search_dropdown/src/helpers/overlay_screen.dart:23:19)
#2      SearchDropDownState.build.<anonymous closure> (package:simple_search_dropdown/src/single/simple_search_dropdown.dart:370:27)
#3      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:3672:27)
#4      EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:2870:7)
#5      TextInput._updateEditingValue (package:flutter/src/services/text_input.dart:2019:43)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1852:29)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
====================================================================================================
```

Here is my code:
```
Widget simpleSearchDropdown(SearchViewModel searchModel) {
    return SearchDropDown(
      key: singleSearchKey,
      listItems: (searchSelection == cTankLineSearch) ? searchModel.returnTankLinesAsValueItems():returnEmptyTankLineValueList(),
      onAddItem: addItem,
      addMode: false,
      deleteMode: false,
      updateSelectedItem: updateSelectedItem,
      selectedItem: null,
      hint: "Select a tank line",
    );
  }
```

**Comment by Macacoazul01** [comment]
Can you send a full main.dart file with the sample code?

**Comment by mauricev** [comment]
The project is at [https://github.com/mauricev/aquarius](url). The file with your plugin is [https://github.com/mauricev/aquarius/blob/main/lib/views/search_view.dart](url)

**Comment by Lorenzobettega** [comment]
> : No element

Try generating the list outside the dropdown.

Instead of this:
`listItems: (searchSelection == cTankLineSearch) ? searchModel.returnTankLinesAsValueItems():returnEmptyTankLineValueList(),`

do something like this:

`final list = (searchSelection == cTankLineSearch) ? searchModel.returnTankLinesAsValueItems():returnEmptyTankLineValueList();`

`listItems: list`

We couldn't reproduce the error with your code because we werent able to pass the login or register screen of the app.

If you can, please send a custom sample detached from the app or send more info of the error that we can use to reproduce in the custom sample (or another code).

**Comment by Macacoazul01** [comment]
The error is happening because the code tries to access an element that doesnt exist. Maybe the solution above can help you, but the problem seems code related, not package related

**Comment by mauricev** [comment]
I don't follow how my code has anything to do with this error. I select an element and then delete its last character. updateSelectedItem isn’t being called when that happens as far as I can tell. Only your code is running when it produces the no element exception.

**Comment by Macacoazul01** [comment]
If something changes on the list because the way you are generating it. The element wont exist anymore and the error will be present.

Please send us a sample with the error (outside of your app code) that we can use to test.

With your app we cant create an account to see the error and also there's a lot there that isnt related to the package.

With this sample we can isolate the error.

**Comment by mauricev** [comment]
In the particular dropdown where this is occurring, when I select an item from the dropdown, it gets entered into the searchbar, the dropdown disappears and the _searchbar’s text field remains active with a blinking cursor_. At this point, I delete a character and of course, since the dropdown had been deleted, you removed the list, and the exception occurs. I have absolutely no idea why in my particular widget tree, the searchbar’s text field is left alive. As far as I can see in your code, you merely assign the selected item to the text controller and that’s all. What’s also weird is why is it occurring in my specific widget tree and nowhere else.

**Comment by mauricev** [comment]
That appears to fix it. Thanks.
