### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by tekink** [Lorenzobettega/simplesearchdropdown#22]
Scroll does not remember the position, it resets to the beginning every time.
![1](https://github.com/Lorenzobettega/simplesearchdropdown/assets/88088517/02ab0c5e-d00b-453f-bc55-13522138917d)
I select item
![2](https://github.com/Lorenzobettega/simplesearchdropdown/assets/88088517/1cf8744c-a7ab-45d3-9a40-ff493e7e5942)
i don't scrool same position when i re-click it.

**Comment by Macacoazul01** [comment]
I'm not sure if this should be implemented, when thinking about the problems that could cause. 

If the list changes between the first and the second click, what do you expect to happen?

**Comment by Macacoazul01** [comment]
Not just thinking if something was added or removed, but if you clicked on the 'x' to clear the selection.

**Comment by Macacoazul01** [comment]
When the widget must maintain the position and when not? While the screen is presented or this should be "definitive" for the app session?

**Comment by tekink** [comment]
> I'm not sure if this should be implemented, when thinking about the problems that could cause.
> 
> 1-If the list changes between the first and the second click, what do you expect to happen? 1.1- Not just thinking if something was added or removed, but if you clicked on the 'x' to clear the selection.

-1-List not changed, same screen and data. I want to select items ascending order. For example; When I select an item that starts with z, when I press arrow again, the list starts with the letter a.


https://github.com/Lorenzobettega/simplesearchdropdown/assets/88088517/67cffcd0-86da-46fa-adff-84bed9dd9167

**Comment by Macacoazul01** [comment]
Here im not thinking only on your context. Your list didn't, but someones might change.

**Comment by Macacoazul01** [comment]
Created another issue for list ordering

**Comment by tekink** [comment]
Thanks for update, it behaivors nice. But selected item not ordering middle of overlay.

https://github.com/Lorenzobettega/simplesearchdropdown/assets/88088517/03508f86-cf93-4078-b92f-68e38adc944d

**Comment by tekink** [comment]
```
 void goToSelectedItem(ScrollController controller, ValueItem<T> item) {
    final index = listaFiltrada.indexOf(item);
    if (index > 0) {
      final contentSize = controller.position.viewportDimension +
          controller.position.maxScrollExtent;

      final target = contentSize * index / listaFiltrada.length;
      controller.position.animateTo(
        target,
        duration: const Duration(milliseconds: 1000),
        curve: Curves.easeOut,
      );
    }
  }
```
i tried to change somethings in this code, but it didn't success.
`target-(dialogHeight/2) `

**Comment by Macacoazul01** [comment]
We are still developing the feature (with a big refactor in the variables and docs).
If i have time to, gonna finish this week.

**Comment by tekink** [comment]
```
Widget dropdown<T>({
  required List<ValueItem<T>> items,
  required String hint,
  required Function(ValueItem val) onSelect,
}) {
  return dropContainer(
      child: Container(
        width: Get.width,//Get.width:from Get plugin
        child: SearchDropDown<T>(
          listItems: items,
          addMode: false,
          deleteMode: false,
          updateSelectedItem: (val) async {
            
          },
          onAddItem: (ValueItem<T> val) {},
          elevation: 1,
          backgroundColor: Colors.blue,
          hoverColor: Colors.white,
          selectedDialogColor: Colors.white,
          selectedInsideBoxTextStyle: TextStyle(color: Colors.black),
          unselectedInsideBoxTextStyle: TextStyle(color: Colors.white),
          sortSelecteds: false,
          separatorHeight: 0,
          clearIconColor: Colors.black,
          unselectedItemHoverColor: Colors.yellow,
          selectedItemHoverColor: Colors.white,
          hint: hint,
          dialogBackgroundColor: Colors.blue,
          border: const RoundedRectangleBorder(
              borderRadius: BorderRadius.all(Radius.circular(40)),
              side: BorderSide(color: Colors.red, width: 30, strokeAlign: 5)),
        ),
      ),
      border: false);
}
```

Widget studentDropdown() {
  return dropdown<String>(
      items:studentList.map((e) => ValueItem(label: e.name, value: e.id)).toList(),
      hint: "Select Student",
      onSelect: (val) async {
        
      });
}

**Comment by tekink** [comment]
> Can you send a sample list that breaks the code and how you are constructing the dropdown?
This is my function

```
Widget dropdown<T>({
  required List<ValueItem<T>> items,
  required String hint,
  required Function(ValueItem val) onSelect,
}) {
  return dropContainer(
      child: Container(
        width: Get.width,
        child: SearchDropDown<T>(
          listItems: items,
          addMode: false,
          deleteMode: false,
          updateSelectedItem: (val) async {

          },
          onAddItem: (ValueItem<T> val) {},
          elevation: 10,
          backgroundColor: Colors.black,
          overlayListSettings: SimpleOverlaySettings(
          selectedItemBackgroundColor: Colors.white,
            selectedItemHoverColor: Colors.white,
            unselectedItemHoverColor: Colors.black,
            unselectedItemTextStyle: TextStyle(color: Colors.white)
          ),
          searchBarSettings: SimpleSearchbarSettings(
            clearOnClose: false,
            hint: hint,
            hoverColor: Colors.white,
            hintStyle: TextStyle(color: Colors.black, fontStyle: FontStyle.italic),
            border: const RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(40))),
          ),
          dialogBackgroundColor: Renk.appBarBackground,
        ),
      ),
      border: false);
}
```
This is sample
```
Widget teacherDropdown() {
  gizle();
  return dropdown<ModelTeacher>(
      items:
      teacherList.map((e) => ValueItem(label: e.name, value: e)).toList(),
      hint: "Select Teacher",
      onSelect: (val) async {

      });
}
```

**Comment by Macacoazul01** [comment]
updated on 4.0
