### ISSUE TITLE
width fixed at 300

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#31]
I can’t seem to set a width less than 300. I'm inside a container which is set at 300, but when I pass 220 for the width to searchBarSettings, it gets ignored. Reducing the height does work.

**Comment by Lorenzobettega** [comment]
I tried a lot of ways to correct this with usual methods, but seachbar in included in material 3 that have a unstable size property.
Regardless of this, I found a possible parcial solution for this problem, will be able in next version (4.0.3)

**Comment by Lorenzobettega** [comment]
The problem persisted so I will continue trying solution until the next update.
