### ISSUE TITLE
changing text font

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#32]
How can I change the font of the searchbar itself? I can change the font of the items, however.

**Comment by Lorenzobettega** [comment]
I put it in [last commit](https://github.com/Lorenzobettega/simplesearchdropdown/commit/a032624c2ca9a9bd2399e2c8ba35030ac579146c), you can acess this option using:
`searchBarSettings: SimpleSearchbarSettings(searchBarTextStyle: TextStyle(color: Colors.red)),`

I will add in next version 4.0.3

**Comment by Macacoazul01** [comment]
Avaliable in 4.0.3
