### ISSUE TITLE
make searchbar lose the focus after selection

### ISSUE THREAD

**Issue by Macacoazul01** [Lorenzobettega/simplesearchdropdown#35]
You can try making the searchbar lose the focus after selection, using something like:

`FocusScope.of(context).unfocus();`

Maybe we should do this in the package too (it possibly will fix another problem)... 

_Originalmente postado por @Macacoazul01 em https://github.com/Lorenzobettega/simplesearchdropdown/issues/21#issuecomment-1843767230_

**Comment by Lorenzobettega** [comment]
Review if this correction is needed after 4.1.0, because the main problem was fixed
