### ISSUE TITLE
Two clicks needed for cell to work

### ISSUE THREAD

**Issue by Macacoazul01** [Lorenzobettega/simplesearchdropdown#36]
Sometimes two clicks on the cell are necessary for the item to be selected.

If we remove the key from `DefaultListTile` everything works fine but the widget wont scroll

**Comment by Lorenzobettega** [comment]
Fixed on this [commit](https://github.com/Lorenzobettega/simplesearchdropdown/commit/270c0c1a6b9483658af711547e20b8e67eaa7b32)
