### ISSUE TITLE
can the opening position be adjusted?

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#39]
My dropdown is near the bottom edge of the iPad, so when it opens, it opens downward and thus gets cut off. It would be nice if it could open upward instead by detecting how many available pixels there are above and below and picking the side with the most free pixels on screen.

**Comment by Macacoazul01** [comment]
The dropdown was suposed to open on top of the box if there isnt enough space.
Can you send some prints/sample code.

Without this I can think in two options:
1-Add an offset so you can move the position up/down/left/right.
2-Add a parameter to force it to open always on top.

**Comment by Macacoazul01** [comment]
try using `4.3.0` and changing `overlayListSettings.offsetWidth` and `overlayListSettings.offsetHeight` to see if this solves your problem

**Comment by mauricev** [comment]
overlayListSettings.offsetHeight works nicely. It would super cool if the dropdown sensed where in space it would appear and then self-addressed overlayListSettings.offsetHeight to a better value all on its own, but it definitely works if I manually set it. Thanks!

**Comment by Macacoazul01** [comment]
Gonna close this because i really dont know how to solve the issue now. If you think in an option, please reach me
