### ISSUE TITLE
can't set font size of multiply chosen items

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#40]
Consider this MultipleSearchDropDown

[https://i.ibb.co/9wFyYH6/Screenshot-2024-03-14-at-12-08-47-AM.jpg](url)
(For whatever reason, you have to manually select and copy the link.)

The font size is too big. I want 10 point, but this is not that. 

Here is my code
```
SimpleSearchbarSettings searchBarSettings = const SimpleSearchbarSettings(
        dropdownHeight: 34,
        dropdownWidth: 220,
        searchBarTextStyle: TextStyle(fontSize: 10),
        hintStyle: TextStyle(fontSize: 10),
        hint: "Select parents");
    SimpleOverlaySettings overlayListSettings = const SimpleOverlaySettings(
        dialogHeight: 400,
        selectedItemTextStyle: TextStyle(fontSize: 10, color: Colors.black),
        unselectedItemTextStyle: TextStyle(fontSize: 9, color: Colors.black45),
        offsetHeight: -250);

    return MultipleSearchDropDown(
      key: parentsDropDownKey,
      listItems: theTankLines,
      onAddItem: addItem,
      addMode: false,
      deleteMode: false,
      updateSelectedItems: updateSelectedParents,
      selectedItems:
      selectedParents, // this doesn’t get reapplied when we change the selected tank, so we give it a unique key to force rebuilding
      searchBarSettings: searchBarSettings,
      overlayListSettings: overlayListSettings,
    );
```
It seems that for plain SearchDropDown, the hintStyle affects the font size that appears in the searchbar. I don't set searchBarTextStyle for it, but even setting it here, doesn’t seem to affect the size of the multiple elements.

**Comment by Macacoazul01** [comment]
You need to change the style of the selected items. I dont remember the exact name of the parameter right now, but I can look later tonight in the code if you dont find it by yourself in the meantime
