### ISSUE TITLE
can i hide the keyboard?

### ISSUE THREAD

**Issue by mauricev** [Lorenzobettega/simplesearchdropdown#42]
Sometimes, I just want the user to select the item without the help of the keyboard. Can I disable the keyboard somehow?

**Comment by Macacoazul01** [comment]
Found a way to do this but then the keyboard would never show up with the setting activated (on the first tested implementation).

Is this the expected behavior?

**Comment by Macacoazul01** [comment]
Done in 6.0
Feel free to open another issue if needed
